context:
  version: "1.5.1"

package:
  name: bzip3
  version: ${{ version }}

source:
  url: https://github.com/kspalaiologos/bzip3/archive/${{ version }}.tar.gz
  sha256: 1116c5984c87c2193f3981b53669c8cbb4ffd1b158de880be3c5ff27a35db400

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
  run_exports:
    - ${{ pin_subpackage('bzip3') }}

tests:
  - script:
      - bzip3 --help

about:
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: A better and stronger spiritual successor to BZip2.
  homepage: https://github.com/kspalaiologos/bzip3
  repository: https://github.com/kspalaiologos/bzip3

extra:
  recipe-maintainers:
    - danielnachun
